function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  X9:  vector of x data
%  Y9:  vector of y data
%  X10:  vector of x data
%  Y10:  vector of y data
%  X11:  vector of x data
%  Y11:  vector of y data
%  X12:  vector of x data
%  Y12:  vector of y data
%  X13:  vector of x data
%  Y13:  vector of y data
%  X14:  vector of x data
%  Y14:  vector of y data
%  X15:  vector of x data
%  Y15:  vector of y data
%  X16:  vector of x data

%  Auto-generated by MATLAB on 06-Jun-2021 14:20:35

% Create figure
figure1 = figure('Clipping','off');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','1','MarkerSize',12,'Marker','*','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0.466666666666667 0.674509803921569 0.188235294117647]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'Nexus1'},...
    'Position',[0.97804956808058 0.89799213809806 1.4210854715202e-14]);

% Create plot
plot(X2,Y2,'DisplayName','2','MarkerSize',12,'Marker','*','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0.466666666666667 0.674509803921569 0.188235294117647]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'GalaxyS'},...
    'Position',[0.97485594728919 0.951064152946607 1.4210854715202e-14]);

% Create plot
plot(X3,Y3,'DisplayName','3','MarkerSize',12,'Marker','*','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0.466666666666667 0.674509803921569 0.188235294117647]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'PVM2551MD'},...
    'Position',[0.962460182114526 0.961716710252733 1.4210854715202e-14]);

% Create plot
plot(X4,Y4,'DisplayName','4','MarkerSize',12,'Marker','x','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'MDCC6130'},...
    'Position',[0.948106421714476 0.972643180301716 1.4210854715202e-14]);

% Create plot
plot(X5,Y5,'DisplayName','5','MarkerSize',12,'Marker','+','LineWidth',3,...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'CG243W'},...
    'Position',[0.945814750437031 0.982222381853119 1.4210854715202e-14]);

% Create plot
plot(X6,Y6,'MarkerSize',12,'Marker','+','LineWidth',3,'LineStyle','none',...
    'Color',[0 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'Z24X'},...
    'Position',[0.92946026801178 0.95956490174456 1.4210854715202e-14]);

% Create plot
plot(X7,Y7,'MarkerSize',12,'Marker','+','LineWidth',3,'LineStyle','none',...
    'Color',[0 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'PA271W'},...
    'Position',[0.910338687967702 0.981175126197389 1.4210854715202e-14]);

% Create plot
plot(X8,Y8,'MarkerSize',12,'Marker','o','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'Cinema'},...
    'Position',[0.895092683561768 0.971291738284024 1.4210854715202e-14]);

% Create plot
plot(X9,Y9,'MarkerSize',12,'Marker','o','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'ZR2240W'},...
    'Position',[0.913077477941123 0.944532450929281 1.4210854715202e-14]);

% Create plot
plot(X10,Y10,'MarkerSize',12,'Marker','o','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'ZR2440W'},...
    'Position',[0.921516090022814 0.927664004251019 1.4210854715202e-14]);

% Create plot
plot(X11,Y11,'MarkerSize',12,'Marker','o','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'1907FP'},...
    'Position',[0.88846868739253 0.949783993557648 1.4210854715202e-14]);

% Create plot
plot(X12,Y12,'MarkerSize',12,'Marker','o','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'P2212Hb'},...
    'Position',[0.893387347255901 0.931709789588454 1.4210854715202e-14]);

% Create plot
plot(X13,Y13,'MarkerSize',12,'Marker','^','LineWidth',3,'LineStyle','none',...
    'Color',[0 1 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'iPhone4'},...
    'Position',[0.883267786406646 0.959825088454966 1.4210854715202e-14]);

% Create plot
plot(X14,Y14,'MarkerSize',12,'Marker','v','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'SM2233RZ'},...
    'Position',[0.914864006226345 0.749618428518472 1.4210854715202e-14]);

% Create plot
plot(X15,Y15,'MarkerSize',12,'Marker','v','LineWidth',3,'LineStyle','none',...
    'Color',[1 0 1]);

% Create text
text('Parent',axes1,'Interpreter','none','String',{'PLCMHD70'},...
    'Position',[0.831209322119016 0.80383081556153 1.4210854715202e-14]);

% Create plot
plot(X16,X16,'LineStyle',':','Color',[0 0 0]);

% Create zlabel
zlabel('ZLabel');

% Create ylabel
ylabel('Gray Tracking (G_AUC)','Interpreter','none');

% Create xlabel
xlabel('Color Tracking (C_AUC)','Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.8 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.7 1]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.14112500343658 0.705 0.13387499656342 0.198687496714294],...
    'Interpreter','none',...
    'FontSize',12);
title(legend1,'Intended Market');

